ERROR : Error appeared during Puppet run: 10.0.2.4_controller.pp
Notice: /Stage[main]/Nova::Db::Sync/Exec[nova-db-sync]/returns: Error: (pymysql.err.OperationalError) (1045, "Access denied for user 'nova'@'centos-openstack.internal.cloudapp.net' (using password: YES)")
You will find full trace in log /var/tmp/packstack/20200918-200511-ovf8u095/manifests/10.0.2.4_controller.pp.log
Please check log file /var/tmp/packstack/20200918-200511-ovf8u095/openstack-setup.log for more information
Additional information:
 * Parameter CONFIG_NEUTRON_L2_AGENT: You have chosen OVN Neutron backend. Note that this backend does not support the VPNaaS or FWaaS services. Geneve will be used as the encapsulation method for tenant networks
 * A new answerfile was created in: /root/packstack-answers-20200918-200511.txt
 * Time synchronization installation was skipped. Please note that unsynchronized time on server instances might be problem for some OpenStack components.
 * File /root/keystonerc_admin has been created on OpenStack client host 10.0.2.4. To use the command line tools you need to source the file.
 * To access the OpenStack Dashboard browse to http://10.0.2.4/dashboard .
Please, find your login credentials stored in the keystonerc_admin in your home directory.